name = "CSMP XI"
author = "CapivaraManca"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "e781912f796e218f3efc96ba7d5970df6f1d67b2463503e2189f0e8366cd4bf0"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.190"
