name = "CSMP XI"
author = "CapivaraManca"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "562601da255d52d31044faab34a446f8e00bd68f268723fbc4bee7ad84e87d88"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.190"
