name = "CSMP XI"
author = "CapivaraManca"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "4d6a59c965e3f911c1cd2197315832346ca5fd5208f69c19fcfde1262c201903"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.169"
