name = "CSMP XI"
author = "CapivaraManca"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "acb3f05e073cd3ac9260526dae002974b878001de7940d979a5a7588264a9d76"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.169"
