name = "CSMP XI"
author = "CapivaraManca"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "86a2b71fcca423357c898255eb543d9f09f092446628f0593b2a5126cd97e950"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.169"
